### ISSUE TITLE
De-fork

### ISSUE THREAD

**Issue by hroncok** [fedora-python/python-ethtool#1]
If this is a new upstream, please detach the fork and turn it into a standalone repository:

> To detach the fork and turn it into a standalone repository on GitHub, contact [GitHub Support](https://github.com/contact). If the fork has forks of its own, let support know if the forks should move with your repository into a new network or remain in the current network. For more information, see "[About forks](https://help.github.com/articles/about-forks/)." ([source](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork))

**Comment by frenzymadness** [comment]
Email with request sent.
