### ISSUE TITLE
setup.py improvements

### ISSUE THREAD

**Issue by hroncok** [fedora-python/python-ethtool#12]
* [ ] `setup.py` does stuff even when `--help` is used (ready in https://github.com/fedora-python/python-ethtool/pull/14)
* [x] `license` attribute is missing
* [x] `classifiers` are missing
* [x] `maintainer` and `maintainer_email` is missing
* [x] `long_description` is missing (combine README with CHANGES)
* [x] `keywords` are missing

**Comment by hroncok** [comment]
I'll dive into the first thing (`setup.py` does stuff even when `--help` is used) as that might not be so easy.

**Comment by Sanqui** [comment]
distutils have no standard way to provide multiple authors or maintainers.  Are all four maintainers' emails to be listed anyway?

**Comment by hroncok** [comment]
list `python-maint@redhat.com`
