### ISSUE TITLE
Call this just ethtool

### ISSUE THREAD

**Issue by hroncok** [fedora-python/python-ethtool#22]
The name `python-ethtool` is kind of a name of an RPM package rather than a Python package/project. Although the repo name `python-ethtool` might be fine to distinguish between this and the real ethtool, I would reference to the tool as `Python ethtool` in the README. Note that both the module and the package are already called just `ethtool`. Thoughts?

**Comment by stratakis** [comment]
I would prefer to not name it simply ethtool, to avoid potential conflicts. py-ethool or ethtool-py might server our case better? Although I don't really like these names. Any other ideas?

**Comment by hroncok** [comment]
This is what I'm proposing:

# Before:

## python-ethtool

*Python bindings for the ethtool kernel interface*

`python-ethtool` allows querying...

`python-ethtool` also provides...

`python-ethtool` is free software ...

# Afeter:

## Python ethtool module

*Python bindings for the ethtool kernel interface*

Python `ethtool` module allows querying...

`ethtool` also provides...

Python `ethtool` module is free software ...

**Comment by Sanqui** [comment]
What about `pethtool`?  That is how the `ethtool` utility clone is called as well.

**Comment by hroncok** [comment]
I don't want to rename this. The module name is `ethtool` and changing it would not help anything.

**Comment by hroncok** [comment]
Bumping this.

**Comment by Sanqui** [comment]
I wrote some discussion over the topic of module and project naming, but then I realized my only issue with your suggestion is probably the missing article in your sentences.

If Python is being used as an adjective in those sentences, I believe what we should write is:
>The Python `ethtool` module allows querying...
>`ethtool` also provides...
>The Python `ethtool` module is free software ...

I'd be fine with this.

**Comment by hroncok** [comment]
@Sanqui agreed. will edit.

**Comment by stratakis** [comment]
After giving it some thought I'd say we move forward and change how the module is referenced in the readme according to @hroncok 's suggestions.
