### ISSUE TITLE
Run tests in some CI

### ISSUE THREAD

**Issue by hroncok** [fedora-python/python-ethtool#3]
Probably Travis CI.

**Comment by hroncok** [comment]
@stratakis Could you tell me, how to run tests? :) I'm getting a lot of compilation errors on my setup.

**Comment by stratakis** [comment]
Not sure how stable the project is at the moment. The compilation was fine till 0.11. After that there were some commits that added partial python3 support and a bogus release (0.12) was done with these. I essentially replicated the release on github to bring the project on par with its previous state from fedorahosted.

With these in mind, the 0.12 release might not even compile. The code will have to be fixed/refactored first.

**Comment by hroncok** [comment]
![facepalm](https://cloud.githubusercontent.com/assets/2401856/24291010/7ab81a64-1087-11e7-8853-b7871b7c93d6.gif)

Ok, let me try to run test on 0.11 and I'll setup the CI anyway, so we know how bad things are.

**Comment by hroncok** [comment]
So I took ed93ee07e25eee26da541ea0b68e33a1bb466992 from Fedora dist-git and now it compiles.

**Comment by frenzymadness** [comment]
I am working on it.

**Comment by hroncok** [comment]
> I am working on it.
Actually, i'm already, sorry about that. What's your status?

**Comment by frenzymadness** [comment]
I am trying to compile it and run tests to be able to explain the installation to readme.

But it might be a good idea to go back in history to the working version 0.11 and then refractor commits.

**Comment by hroncok** [comment]
It compiles now in master. 0.11 didn't compile either. There was a patch in Fedora dist-git.
