### ISSUE TITLE
Link speed and autoneg

### ISSUE THREAD

**Issue by briancline** [fedora-python/python-ethtool#32]
The readme suggests link speed and autonegotiation can be queried and set, but in a cursory glance throughout it doesn't appear this is implemented. I might be wrong though.

Can you provide an example showing how to query link speed and autonegotiation?

**Comment by hroncok** [comment]
> The readme suggests link speed and autonegotiation can be queried and set

Where exactly is this suggested?

**Comment by briancline** [comment]
It's in the intro section.
https://github.com/fedora-python/python-ethtool/blame/24e976fd9c0652c767f937ef7ae6e1de6e712373/README.rst#L7

**Comment by Sanqui** [comment]
`pethtool` allows for setting coalesce and ring parameters, see [usage](https://github.com/fedora-python/python-ethtool/blob/master/scripts/pethtool#L23).  Granted, this is fairly specific kernel settings and not exactly what the README says, so it should probably be changed.

**Comment by hroncok** [comment]
@Sanqui Could you please update the README?

**Comment by Sanqui** [comment]
#33 changes the README to be a bit less specific and more in line with the descriptions of the tools.

**Comment by briancline** [comment]
Thanks for clarifying a bit and for the quick responses. Are there any plans/desires for python-ethtool to support link speeds and auto-negotiation settings in the future?

**Comment by frenzymadness** [comment]
We took the maintenance of ethtool because we need Python 3 support but unfortunately, we don't have enough time to extend functionalities.

But if you want to add something, feel free to open PR and we'll do a review of your changes. Any help will be very appreciated.
