### ISSUE TITLE
Offloading: adding set_gso(), get_gro() and set_gso()

### ISSUE THREAD

**Issue by RemyDelion** [fedora-python/python-ethtool#37]
Hello,
As I needed these 3 functions, I created them locally. Please could you allow me to push the updates on a new branch? Next I will create the corresponding PR.
Thanks in advance,
Regards,
Remy

**Comment by stratakis** [comment]
Hello @RemyDelion and thanks for your interest in python-ethtool. You can fork the repository on github and push your changes there, either to your master or to a different branch of your repo.

Then you should have a button to create a PR against our repository, and we can review your code.

Please post here if you require more help in regards to this issue or the procedure.

**Comment by frenzymadness** [comment]
Here you can find a simple howto https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by RemyDelion** [comment]
Thank you!
Id did the PR https://github.com/fedora-python/python-ethtool/pull/38.

**Comment by frenzymadness** [comment]
Closing this issue

**Comment by RemyDelion** [comment]
Hi frenzymadness,
Did you merge the PR https://github.com/fedora-python/python-ethtool/pull/38?
I can't see the updated files in Master or libnl-1 branches...
Regards,
Remy

**Comment by frenzymadness** [comment]
Hello.

No, I've just closed this issue where we discussed how to create a PR without special rights. PR #38 is still open and waiting for a second review.

If you want, we can keep both (issue and PR) open.
