### ISSUE TITLE
Support for reading the standard information about device

### ISSUE THREAD

**Issue by sshajiya** [fedora-python/python-ethtool#44]
Hi Team,

Thanks for the fantastic library support for ethtool in Python.
There is much support given for many options. Unfortunately, I'm unable to get the  basic standard information about device like ethtool eth0 which will give the below standard info
# ethtool eth0
Settings for eth0:
	Supported ports: [ TP MII ]
	Supported link modes:   10baseT/Half 10baseT/Full 
	                        100baseT/Half 100baseT/Full 
	                        1000baseT/Half 1000baseT/Full 
	Supported pause frame use: No
	Supports auto-negotiation: Yes
	Advertised link modes:  10baseT/Half 10baseT/Full 
	                        100baseT/Half 100baseT/Full 
	                        1000baseT/Full 
	Advertised pause frame use: Symmetric Receive-only
	Advertised auto-negotiation: Yes
	Link partner advertised link modes:  10baseT/Half 10baseT/Full 
	                                     100baseT/Half 100baseT/Full 
	                                     1000baseT/Full 
	Link partner advertised pause frame use: No
	Link partner advertised auto-negotiation: Yes
	Speed: 1000Mb/s
	Duplex: Full
	Port: MII
	PHYAD: 0
	Transceiver: internal
	Auto-negotiation: on
	Supports Wake-on: pumbg
	Wake-on: g
	Current message level: 0x00000033 (51)
			       drv probe ifdown ifup
	Link detected: yes

I would like to read and write the above options using the library python-ethtool, Currently I'm not able to do this. 
Is the support is given in python-ethtool for the above, If so kindly let me know where I'm missing.
Thanks in advance.

**Comment by frenzymadness** [comment]
Hello.

Thank you for your interest. Unfortunately, the purpose of this fork was to make ethtool compatible with Python 3 and fix some bugs and we have no time to add new features.

If you are interested in ethtool, any PR will be very appreciated. I'll do my best to help you as much as I can.

Have a nice day.
Lumír

**Comment by hroncok** [comment]
python-ethtool is maintenance only now. sorry

**Comment by frenzymadness** [comment]
But still, feel free to send a pull request :wink:
