### ISSUE TITLE
Recommend insights-core instead of netifaces

### ISSUE THREAD

**Issue by Ashark** [fedora-python/python-ethtool#57]
Readme says:
> No new development is happening. This is a deprecated package. If you are considering to start using this, please don't. We recommend netifaces instead.

The netifaces seems to be dead, and is unable to do anythyng besides getting addresses info.
Better recommendation could be [ethtool parser](https://insights-core.readthedocs.io/en/latest/shared_parsers_catalog/ethtool.html) frrom insights-core.

**Comment by frenzymadness** [comment]
What about listing them both and letting the users choose? More alternatives mean less probability they stay here.

**Comment by hroncok** [comment]
:+1:

**Comment by frenzymadness** [comment]
@Ashark could you please prepare a PR?
