### ISSUE TITLE
Remove SPEC file from the source code

### ISSUE THREAD

**Issue by stratakis** [fedora-python/python-ethtool#7]
Is there any reason to keep it in the sources? It's a maintenance burden with no real advantages from the upstream POV.

**Comment by hroncok** [comment]
My thoughts exactly. Drop it.

**Comment by stratakis** [comment]
It seems that the makefile uses it somehow though

**Comment by stratakis** [comment]
Not sure if there are any usecases for the recipes that use the SPEC

**Comment by stratakis** [comment]
Thinking if we should drop the Makefile as well.

**Comment by hroncok** [comment]
Yes.

**Comment by frenzymadness** [comment]
I think that we can drop both of them. I'm gonna do it.
